version: "3.8"

services: 
  traefik:
    # The latest official supported Traefik docker image
    image: traefik:v2.3
    # Enables the Traefik Dashboard and tells Traefik to listen to docker
    # --providers tell Traefik to connect to the Docker provider
    # enable --log.level=INFO so we can see what Traefik is doing in the log files
    # command: --api.insecure=true --providers.docker --log.level=INFO
    ports:
      # Exposes port 80 for incomming web requests
      - "80:80"
      - "443:443"
      # The Web UI port http://0.0.0.0:8080 (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik-entrypoints.yml:/etc/traefik/traefik.yml
      - ./:/usr/src/app
      
  figure2style-api:
    image: figure2style-api
    build: 
      context: .
      dockerfile: Dockerfile
    volumes: 
      - .:/app
      - '/app/node_modules'
    depends_on: 
      - mysql_server
    labels:
       - "traefik.enable=true"
       - "traefik.http.routers.figure2style-api.rule=Host(`51.254.119.169`,`perintos.fr`, `hello.perintos.fr` )"
       - "traefik.http.routers.figure2style-api.service=figure2style-api"
       - "traefik.http.services.figure2style-api.loadbalancer.server.port=3000"
       - "traefik.http.routers.figure2style-api.entrypoints=websecure"
       - "traefik.http.routers.figure2style-api.tls.certresolver=myresolver"

  mysql_server:
    image: mysql:8.0
    environment: 
      - MYSQL_DATABASE=stylistic_device_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
