INSERT INTO example(id_stylistic_device,author,text) VALUE(?, "Victor Hugo"       , "Je vis cette faucheuse. Elle était dans son champ. Elle allait à grands pas moissonnant et fauchant, noir squelette laissant passer le crépuscule.");
INSERT INTO example(id_stylistic_device,author,text) VALUE(?, "Jean Racine"       , "Pour qui sont ces serpents qui sifflent sur vos têtes ?");
INSERT INTO example(id_stylistic_device,author,text) VALUE(?, "Blaise Pascal"     , "Le nez de Cléopâtre, s'il eût été plus court, la face du monde en eût été changée.");
INSERT INTO example(id_stylistic_device,author,text) VALUE(?, "Pierre Corneille"  , "Je veux, sans que la mort ose me secourir. Toujours aimer, toujours souffrir, toujours mourir.");
INSERT INTO example(id_stylistic_device,author,text) VALUE(?, ""                  , "Quel courage ! s'excalmat l'interlocuteur qui designait en fait ça lâcheté");
INSERT INTO example(id_stylistic_device,author,text) VALUE(?, "Pierre Corneille"  , "À vaincre sans péril, on triomphe sans gloire.");
INSERT INTO example(id_stylistic_device,author,text) VALUE(?, "Pierre Corneille"  , "Ô rage ! ô désespoir ! ô vieillesse ennemie ! N'ai-je donc tant vécu que pour cette infamie ?");
INSERT INTO example(id_stylistic_device,author,text) VALUE(?, "Jean Racine"       , "Tout m'afflige et me nuit et conspire à me nuire. ");
INSERT INTO example(id_stylistic_device,author,text) VALUE(?, ""                  , "Tu l'as voulu, tu l'as eu");
INSERT INTO example(id_stylistic_device,author,text) VALUE(?, "Molière"           , "Il faut manger pour vivre et non vivre pour manger.");
INSERT INTO example(id_stylistic_device,author,text) VALUE(?, ""                  , "Il court aussit vite que son père.");
INSERT INTO example(id_stylistic_device,author,text) VALUE(?, "André Malraux"     , "Pris ou non, exécuté ou non, peu importait");
INSERT INTO example(id_stylistic_device,author,text) VALUE(?, "Guy de Maupassant" , "Devant eux, sur de petites tables carrées ou rondes, des verres contenaient des liquides rouges, jaunes, verts, bruns, de toutes nuances.");
INSERT INTO example(id_stylistic_device,author,text) VALUE(?, ""                  , "Les non-voyants désignent en réalité les aveugles.");
INSERT INTO example(id_stylistic_device,author,text) VALUE(?, "Molière"           , "Je me meurs ; je suis mort ; je suis enterré");
INSERT INTO example(id_stylistic_device,author,text) VALUE(?, "Baudelaire"        , "Ses yeux polis sont faits de minéraux charmants.  L'adjectif 'charmant' s'applique en fait à 'yeux', et 'polis' à 'minéraux'");
INSERT INTO example(id_stylistic_device,author,text) VALUE(?, ""                  , "Je meurs de faim : j'ai très faim.");
INSERT INTO example(id_stylistic_device,author,text) VALUE(?, ""                  , "On peut dire « Ce n'est pas mauvais ! » pour dire que c'est très bon."                             );
INSERT INTO example(id_stylistic_device,author,text) VALUE(?, ""                  , "Mon patron est un vrai requin.");
INSERT INTO example(id_stylistic_device,author,text) VALUE(?, ""                  , "Il a acheté un Picasso : Il a acheté un tableau de Picasso.");
INSERT INTO example(id_stylistic_device,author,text) VALUE(?, "Gérard de Nerval"  , "Ma seule étoile est morte, - et mon luth constellé. Porte le Soleil noir de la Mélancolie.");
INSERT INTO example(id_stylistic_device,author,text) VALUE(?, "Charles Baudelaire", "Je suis la plaie et le couteau ! Je suis le soufflet et la joue !");
INSERT INTO example(id_stylistic_device,author,text) VALUE(?, ""                  , "Qui se ressemble s'assemble.");
INSERT INTO example(id_stylistic_device,author,text) VALUE(?, ""                  , "Le septième art : le cinéma");
INSERT INTO example(id_stylistic_device,author,text) VALUE(?, "Alphonse Daudet"   , "Le mistral était en colère, et les éclats de sa grande voix m'ont tenu éveillé jusqu'au matin.");
INSERT INTO example(id_stylistic_device,author,text) VALUE(?, "René Descartes"    , "Car d'où est-ce que l'effet peut tirer sa réalité sinon de sa cause ? Et comment cette cause la lui pourrait-elle communiquer, si elle ne l'avait en elle-même ?"                                         );
INSERT INTO example(id_stylistic_device,author,text) VALUE(?, ""                  , "Exprimer la partie pour le tout : Je quitterai bientôt ces murs.   ces murs désignent en réalité la maison.");
INSERT INTO example(id_stylistic_device,author,text) VALUE(?, "Alfred  de Musset ", "Zeugme syntaxique : Ils savent compter l'heure, et que leur terre est ronde.");